---
- hosts: web
  sudo: yes

  tasks: 
  - name: Install Apache Pkg for RedHat.
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Install Apache Pkg for Debian.
    apt: name=apache2 update_cache=yes state=latest
    when: ansible_os_family == "Debian" 	

  - name: Start the Apache Service for RedHat
    service: name=httpd state=started enabled=True
    when: ansible_os_family == "RedHat"

  - name: Start the Apache Service for Debian
    service: name=apache2 state=started enabled=True
    when: ansible_os_family == "Debian"

- hosts: db
  sudo: yes

  tasks: 
  - name: Install MariaDB Pkg.
    yum: name=mariadb-server state=present

  - name: Start the Apache Service
    service: name=mariadb state=started enabled=True

- hosts: all:!db
  sudo: yes

  tasks: 
  - name: Stop the Firewalld Service
    service: name=firewalld state=stopped enabled=False
